name: Nix

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Nix Flake - Linux
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Clone project
        uses: actions/checkout@v4
      - name: Build
        run: nix build
